SELECT 
    PRODUCT_CODE,
    SUM(PRICE * SALES_AMOUNT) AS SALES
FROM 
    PRODUCT P
JOIN 
    OFFLINE_SALE O
USING (PRODUCT_ID)
GROUP BY 
    PRODUCT_CODE
ORDER BY 
    SALES DESC, 
    PRODUCT_CODE ASC;
